PAYPAL_USERNAME = "arturs_api1.creo.mobi"
PAYPAL_PASSWORD = "1370585877"
PAYPAL_SIGNATURE = "AiPC9BjkCyDFQXbSkoZcgqH3hpacAXGhMwDsIVl0-bDXDVkIlvFwO5cx"
PAYPAL_APP_ID = "APP-80W284485P519543T"
PAYPAL_SANDBOX = true
PAYPAL_RECEIVER = "arturs@creo.mobi"
PAYPAL_RECEIVER_LT = "arturs@creo.mobi"
SWISS_PAYPAL_RECEIVER = "vidaga@creo.mobi"


PAYPAL_CURRENCY = "EUR"
ALLOWED_PAYPAL_CURRENCIES = ["EUR", "USD", "GBP", "PLN", "DKK"]