Country.find_or_create_by({title: "Latvia", code: "lv"})
Country.find_or_create_by({title: "Lithuania", code: "lt"})
Country.find_or_create_by({title: "Estonia", code: "ee"})
Country.find_or_create_by({title: "Poland", code: "pl"})
Country.find_or_create_by({title: "United Kingdom", code: "gb"})
Country.find_or_create_by({title: "Ireland", code: "ie"})
Country.find_or_create_by({title: "Finland", code: "fi"})
Country.find_or_create_by({title: "Denmark", code: "dk"})
Country.find_or_create_by({title: "USA", code: "us"})

PageFunctionGroup.find_or_create_by(name: "static")
PageFunctionGroup.find_or_create_by(name: "order")
PageFunctionGroup.find_or_create_by(name: "checkout")
PageFunctionGroup.find_or_create_by(name: "success")